version: '3.9'

services:
  redis:
    image: redis:latest

  mysql:
    image: mysql:latest
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: django_project
      # MYSQL_USER: root
      # MYSQL_PASSWORD: rootpassword
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: .
    image: unknownzyz/web:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_NAME: django_project
      DATABASE_USER: root
      DATABASE_PASSWORD: rootpassword

volumes:
  mysql-data:  # 定义卷
