# Generated by Django 4.2.4 on 2024-04-26 09:01

import Doc.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("DocSet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=Doc.models.doc_file_path)),
                ("name", models.CharField(max_length=100)),
                ("file_size", models.FloatField()),
                ("date", models.DateField()),
                ("remark", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("upload_status", models.CharField(default="Wait", max_length=50)),
                (
                    "docSet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="docs",
                        to="DocSet.docset",
                    ),
                ),
            ],
        ),
    ]
