# Generated by Django 4.2.4 on 2024-05-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='type',
            field=models.CharField(choices=[('AMM', ' '), ('FIM', ' ')], default='AMM', max_length=10),
        ),
    ]
