# Generated by Django 5.0.3 on 2024-04-22 04:09

import Doc.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Doc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doc",
            name="file",
            field=models.FileField(upload_to=Doc.models.doc_file_path),
        ),
    ]
