# Generated by Django 4.2.4 on 2024-04-28 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("DocSet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("history", models.TextField(blank=True, null=True)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "docSet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="DocSet.docset",
                    ),
                ),
            ],
        ),
    ]
